name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Set up Nodejs 14
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
    - name: Install dependencies
      run: make devenv
    - name: Build the extension
      run: |
        set -eux
        jlpm
        jlpm run build
        python -m pip install .

        jupyter labextension list 2>&1 | grep -ie "fugue-jupyter.*OK"
        python -m jupyterlab.browser_check

        pip install build
        python -m build --sdist
        cp dist/*.tar.gz myextension.tar.gz
        pip uninstall -y "fugue_jupyter" jupyterlab
        rm -rf myextension

    - uses: actions/upload-artifact@v2
      with:
        name: myextension-sdist
        path: myextension.tar.gz

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Set up Nodejs 14
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - uses: actions/download-artifact@v2
      with:
        name: myextension-sdist
    - name: Install and Test
      run: |
        set -eux
        pip install myextension.tar.gz
        pip install jupyterlab
        jupyter labextension list 2>&1 | grep -ie "fugue-jupyter.*OK"
        python -m jupyterlab.browser_check --no-chrome-test
    - name: Test Notebook
      run: |
        pip install pytest
        make testnb
