name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: "3.8"
          node_version: '14.x'
      - name: Install dependencies
        run: make devenv
      - name: Build and publish
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          set -eux
          make package
          twine upload dist/*
